# Site settings
title: My Unscripted Life 
header-img: img/home-bg.png
email: teresamarie04@gmail.com
copyright_name: teresamyers
description: > # this means to ignore newlines until "baseurl:"
  Changing my life, one code at a time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  teresamyers
learn_profile: teresamyers
email_username: teresamarie04@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
